server:
  port: "${SERVER_PORT}"
spring:
  application:
    name: "LoanApplications"
  devtools:
    add-properties: false
  sql:
    init:
      mode: "never"
  profiles:
    active: "Prod"
adapters:
  r2dbc:
    host: "${DB_HOST}"
    port: "${DB_PORT}"
    database: "${DB_NAME}"
    schema: "${DB_SCHEMA}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
  sqs:
    region: "${AWS_REGION:us-east-1}"
    publishQueueUrl: "${AWS_SQS_PUBLISH_QUEUE_URL}"
    validateQueueUrl: "${AWS_SQS_VALIDATE_QUEUE_URL}"
    publishReportQueueUrl: "${AWS_SQS_PUBLISH_REPORT_QUEUE_URL}"
entrypoint:
  sqs:
    region: "${AWS_REGION:us-east-1}"
    queueUrl: "${AWS_SQS_PROCESS_QUEUE_URL}"
    waitTimeSeconds: 20
    visibilityTimeoutSeconds: 30
    maxNumberOfMessages: 5
    numberOfThreads: 2
cors:
  allowed-origins: "${CORS_ALLOWED_ORIGINS}"
authentication:
  client:
    base-url: "${AUTHENTICATION_CLIENT_BASE_URL}"
    exists-path: "/api/v1/users/exists/{email}"
    connect-timeout-ms: 3000
    read-timeout-sec: 3
    find-by-email-path: "/api/v1/users/email/{email}"
aws:
  region: "${AWS_REGION:us-east-1}"
  secretName: "prod/CrediYa/LoanApplications/Secrets"
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
logging:
  level:
    com.credi.ya: INFO
    org.springframework: WARN
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
