server:
  port: 8081
spring:
  application:
    name: "LoanApplications"
  devtools:
    add-properties: false
  sql:
    init:
      mode: never
  adapters:
    r2dbc:
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ${DB_NAME}
      schema: ${DB_SCHEMA}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
cors:
  allowed-origins: "http://localhost:8081"
