server:
  port: 8080
spring:
  application:
    name: "LoanApplications"
  devtools:
    add-properties: false
  sql:
    init:
      mode: never
adapters:
  r2dbc:
    host: ${DB_HOST}
    port: ${DB_PORT}
    database: ${DB_NAME}
    schema: ${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
cors:
  allowed-origins: "http://localhost:8081"
authentication:
  client:
    base-url: "${AUTHENTICATION_CLIENT_BASE_URL}"
    exists-path: "/api/v1/users/exists/{email}"
    connect-timeout-ms: 3000
    read-timeout-sec: 3
    find-by-email-path: "/api/v1/users/email/{email}"
security:
  jwt:
    secret: ${JWT_SECRET}